<a href="https://colab.research.google.com/github/edersoncid/EstructuraDatos/blob/main/Lab03_04_Estructura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recursividad:
1.    Ejercicio 1: Escribe una función recursiva que imprima los números pares del 1 al 100.
2.   Ejercicio 2: Escribe una función recursiva que imprima la suma de los números del 1 al n.
3.    Ejercicio 3: Escribe una función recursiva que imprima la pirámide de números del 1 al n.
4.    Ejercicio 4: Escribe una función recursiva que imprima la pirámide de números invertidos del 1 al n. 5)    Ejercicio 2: Escribe una función recursiva que imprima la tabla de multiplicar del n.

# Arreglos y Matrices:

6.   Crea una matriz de números reales.
7.    Crea una matriz de números complejos.
8.   Crea una matriz de matrices.
9.    Accede al elemento central de una matriz.
10.  Suma dos matrices de diferentes tamaños.
11.   Multiplica una matriz por un número.
12.  Calcula la media de los elementos de una matriz.



In [1]:
#Ejercicio 01
def imprimir_pares(n):
    if n == 0:
        return
    imprimir_pares(n - 1)
    if n % 2 == 0:
        print(n)

print("Números pares del 1 al 100:")
imprimir_pares(100)


Números pares del 1 al 100:
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [2]:
#Ejercicio 02
def suma_hasta_n(n):
    if n == 0:
        return 0
    return n + suma_hasta_n(n - 1)

numero = 10
print("Suma de los números del 1 al", numero, ":", suma_hasta_n(numero))


Suma de los números del 1 al 10 : 55


In [3]:
#Ejercicio 03

def piramide(n):
    if n == 0:
        return
    piramide(n - 1)
    print(" " * (n - 1) + str(n) * (2 * (5 - n) + 1))

print("Pirámide de números del 1 al 5:")
piramide(5)


Pirámide de números del 1 al 5:
111111111
 2222222
  33333
   444
    5


In [4]:
#Ejercicio 04

def piramide_invertida(n):
    if n == 0:
        return
    print(str(n) * (2 * (5 - n) + 1))
    piramide_invertida(n - 1)

print("Pirámide de números invertidos del 1 al 5:")
piramide_invertida(5)


Pirámide de números invertidos del 1 al 5:
5
444
33333
2222222
111111111


In [9]:
#Ejercicio 05
# Crear una matriz de números reales
matriz_reales = np.array([[1.2, 2.3, 3.4], [4.5, 5.6, 6.7], [7.8, 8.9, 9.1]])
print("Matriz de números reales:")
print(matriz_reales)

Matriz de números reales:
[[1.2 2.3 3.4]
 [4.5 5.6 6.7]
 [7.8 8.9 9.1]]


In [10]:
#Ejercicio 06
# Crear una matriz de números complejos
matriz_complejos = np.array([[1 + 2j, 3 + 4j], [5 + 6j, 7 + 8j]])
print("\nMatriz de números complejos:")
print(matriz_complejos)


Matriz de números complejos:
[[1.+2.j 3.+4.j]
 [5.+6.j 7.+8.j]]


In [11]:
#Ejercicio 07
# Crear una matriz de matrices
matriz_de_matrices = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nMatriz de matrices:")
print(matriz_de_matrices)



Matriz de matrices:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
#Ejercicio 08
# Acceder al elemento central de una matriz
filas, columnas = matriz_reales.shape
if filas % 2 == 1 and columnas % 2 == 1:
    elemento_central = matriz_reales[filas // 2, columnas // 2]
    print("\nElemento central de la matriz de números reales:", elemento_central)


Elemento central de la matriz de números reales: 5.6


In [16]:
#Ejercicio 09
# Sumar dos matrices de diferentes tamaños
import numpy as np

# Definir las matrices
matriz_a = np.array([[1, 2], [3, 4]])
matriz_b = np.array([[5, 6, 7], [8, 9, 10]])

# Obtener las formas de las matrices
filas_a, columnas_a = matriz_a.shape
filas_b, columnas_b = matriz_b.shape

# Crear nuevas matrices con las mismas dimensiones
if filas_a < filas_b:
    matriz_a = np.pad(matriz_a, ((0, filas_b - filas_a), (0, 0)), mode='constant')
elif filas_b < filas_a:
    matriz_b = np.pad(matriz_b, ((0, filas_a - filas_b), (0, 0)), mode='constant')

if columnas_a < columnas_b:
    matriz_a = np.pad(matriz_a, ((0, 0), (0, columnas_b - columnas_a)), mode='constant')
elif columnas_b < columnas_a:
    matriz_b = np.pad(matriz_b, ((0, 0), (0, columnas_a - columnas_b)), mode='constant')

# Sumar las matrices
suma_matrices = matriz_a + matriz_b

print("Matriz A:")
print(matriz_a)
print("\nMatriz B:")
print(matriz_b)
print("\nSuma de las matrices:")
print(suma_matrices)


Matriz A:
[[1 2 0]
 [3 4 0]]

Matriz B:
[[ 5  6  7]
 [ 8  9 10]]

Suma de las matrices:
[[ 6  8  7]
 [11 13 10]]


In [14]:
#Ejercicio 10
# Multiplicar una matriz por un número
numero = 2
matriz_multiplicada = numero * matriz_a
print("\nMatriz multiplicada por", numero, ":")
print(matriz_multiplicada)


Matriz multiplicada por 2 :
[[2 4]
 [6 8]]


In [15]:
#Ejercicio 12
# Calcular la media de los elementos de una matriz
media = np.mean(matriz_a)
print("\nMedia de los elementos de la matriz de números reales:", media)


Media de los elementos de la matriz de números reales: 2.5
